openapi: 3.0.0
info:
  title: Vapi Webhooks API
servers: 
  - url: https://{yourserver}.com
paths:
  /server:
    post:
      summary: Server Message
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../api/openapi.json#/components/schemas/ServerMessage'
      responses:
        '200':
          description: | 
            This is the response that is expected from the server to the message.

            Note: Most messages don't expect a response. Only "assistant-request", "tool-calls" and "transfer-destination-request" do.
          content:
            application/json:    
              schema:
                $ref: '../api/openapi.json#/components/schemas/ServerMessageResponse'
  /client:
    post:
      summary: Client Message
      description: |
        These are all the webhook messages that will be sent to the client-side SDKs during the call. 
        Configure the messages you'd like to receive in `assistant.clientMessages`.

      requestBody:
        content:
          application/json:
            schema:
              $ref: '../api/openapi.json#/components/schemas//ClientMessage'
      responses:
        '200':
          description: These are the messages that can be sent from client-side SDKs to control the call.
          content:
            application/json:    
              schema:
                $ref: '../api/openapi.json#/components/schemas/ClientInboundMessage'
