const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createExampleCache, fingerprint } = require('./example-cache.cjs');
const { inputDigest } = require('./run.cjs');

function fixture(t) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'fern-cache-test-'));
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  const errors = [];
  const context = {
    spec: { components: { schemas: { Voice: { type: 'string', enum: ['marin'] } } } },
    settings: {},
    errorCollector: { collect(value) { errors.push(value); } },
  };
  const args = { context, propertySchema: { $ref: '#/components/schemas/Voice' }, breadcrumbs: ['voice'], propertyId: 'voice' };
  return { directory, context, args, errors, cache: createExampleCache({ directory, namespace: 'test' }) };
}

test('a new process can reuse an exact result without sharing mutable objects', (t) => {
  const { directory, args, cache } = fixture(t);
  const expected = { userSpecifiedExamples: {}, autogeneratedExamples: { voice: { value: 'marin', missing: undefined } } };
  assert.deepEqual(cache.run(args, () => expected), expected);
  expected.autogeneratedExamples.voice.value = 'changed after conversion';
  const next = createExampleCache({ directory, namespace: 'test' });
  const hit = next.run(args, () => { throw new Error('must be a cache hit'); });
  assert.equal(hit.autogeneratedExamples.voice.value, 'marin');
  assert.ok(Object.hasOwn(hit.autogeneratedExamples.voice, 'missing'));
  hit.autogeneratedExamples.voice.value = 'changed after cache read';
  assert.equal(next.run(args, () => assert.fail()).autogeneratedExamples.voice.value, 'marin');
});

test('schemas, parser settings, property inputs, and namespaces invalidate entries', (t) => {
  const { directory, args, cache } = fixture(t);
  cache.run(args, () => 'old');
  for (const context of [
    { ...args.context, spec: { changed: true } },
    { ...args.context, settings: { changed: true } },
    { ...args.context, generationLanguage: 'python' },
    { ...args.context, smartCasing: true },
    { ...args.context, documentBaseDir: '/different-reference-base' },
  ]) assert.equal(cache.run({ ...args, context }, () => 'new'), 'new');
  assert.equal(cache.run({ ...args, propertySchema: { type: 'number' } }, () => 'new'), 'new');
  assert.equal(createExampleCache({ directory, namespace: 'new-version' }).run(args, () => 'new'), 'new');
});

test('diagnostics are emitted on every run and the collector is restored', (t) => {
  const { args, context, errors, cache } = fixture(t);
  const original = context.errorCollector.collect;
  for (let i = 0; i < 2; i++) {
    cache.run(args, () => { context.errorCollector.collect('invalid example'); return {}; });
    assert.equal(context.errorCollector.collect, original);
  }
  assert.deepEqual(errors, ['invalid example', 'invalid example']);
  assert.equal(cache.stats.hits, 0);
});

test('generation errors propagate and do not poison the cache', (t) => {
  const { args, context, cache } = fixture(t);
  const original = context.errorCollector.collect;
  assert.throws(() => cache.run(args, () => { throw new Error('invalid schema'); }), /invalid schema/);
  assert.equal(context.errorCollector.collect, original);
  assert.equal(cache.run(args, () => 'recovered'), 'recovered');
});

test('cache keys preserve null, undefined, and non-JSON numeric values', (t) => {
  const { args, cache } = fixture(t);
  for (const example of [null, undefined, NaN, Infinity]) {
    const inputs = { ...args, mediaExampleArgs: { example } };
    assert.deepEqual(cache.run(inputs, () => ({ example })), { example });
    assert.deepEqual(cache.run(inputs, () => assert.fail()), { example });
  }
  assert.equal(cache.stats.misses, 4);
  assert.equal(cache.stats.hits, 4);
});

test('fingerprints are stable across key order and shared object identities', () => {
  const shared = { text: 'hello', number: 3 };
  assert.equal(fingerprint({ a: shared, b: shared }), fingerprint({ b: { number: 3, text: 'hello' }, a: { text: 'hello', number: 3 } }));
  assert.notEqual(fingerprint([undefined]), fingerprint(Array(1)));
  assert.notEqual(fingerprint(NaN), fingerprint(['number', 'NaN']));
});

test('corrupt entries fall back to original generation', (t) => {
  const { directory, args, cache } = fixture(t);
  cache.run(args, () => 'old');
  const contextDirectory = path.join(directory, 'test', fs.readdirSync(path.join(directory, 'test'))[0]);
  fs.writeFileSync(path.join(contextDirectory, fs.readdirSync(contextDirectory)[0]), 'corrupt');
  assert.equal(cache.run(args, () => 'regenerated'), 'regenerated');
});

test('API and prose edits preserve the namespace while tooling changes invalidate it', (t) => {
  const { directory } = fixture(t);
  fs.mkdirSync(path.join(directory, 'fern/apis/api'), { recursive: true });
  fs.writeFileSync(path.join(directory, 'fern/fern.config.json'), '{"version":"5.112.0"}');
  fs.writeFileSync(path.join(directory, 'fern/apis/api/openapi.json'), '{}');
  const before = inputDigest(directory);
  fs.writeFileSync(path.join(directory, 'fern/overview.mdx'), 'new prose');
  assert.equal(inputDigest(directory), before);
  fs.writeFileSync(path.join(directory, 'fern/apis/api/ai_examples_override.yml'), 'generated output');
  assert.equal(inputDigest(directory), before);
  fs.writeFileSync(path.join(directory, 'fern/apis/api/overrides.yml'), 'new schema override');
  assert.equal(inputDigest(directory), before);
  fs.writeFileSync(path.join(directory, 'fern/fern.config.json'), '{"version":"different"}');
  assert.notEqual(inputDigest(directory), before);
});

test('unrelated API edits reuse entries across fresh processes', (t) => {
  const { directory, args, cache } = fixture(t);
  cache.run(args, () => 'original');
  const spec = structuredClone(args.context.spec);
  spec.components.schemas.Unrelated = { type: 'number' };
  spec.paths = { '/unrelated': { get: { summary: 'New endpoint' } } };
  const next = createExampleCache({ directory, namespace: 'test' });
  assert.equal(next.run({ ...args, context: { ...args.context, spec } }, () => assert.fail('unrelated edit missed')), 'original');
  assert.equal(next.stats.hits, 1);
});

test('transitive dependencies, cycles, and same-context mutations invalidate affected entries', (t) => {
  const { args, cache } = fixture(t);
  const schemas = args.context.spec.components.schemas;
  schemas.Voice = { type: 'object', properties: { style: { $ref: '#/components/schemas/Style' } } };
  schemas.Style = { enum: ['warm'], parent: { $ref: '#/components/schemas/Voice' } };
  cache.run(args, () => 'warm');
  assert.equal(cache.run(args, () => assert.fail()), 'warm');
  schemas.Style.enum = ['bright'];
  assert.equal(cache.run(args, () => 'bright'), 'bright');
  delete schemas.Style;
  assert.equal(cache.run(args, () => 'missing'), 'missing');
  schemas.Style = { enum: ['soft'] };
  assert.equal(cache.run(args, () => 'soft'), 'soft');
});

test('referenced examples and all union branches contribute dependencies', (t) => {
  const { args, cache } = fixture(t);
  const spec = args.context.spec;
  spec.components.examples = { greeting: { value: 'hello' } };
  spec.components.schemas.Voice = { oneOf: [{ $ref: '#/components/schemas/Other' }], example: { $ref: '#/components/examples/greeting' } };
  spec.components.schemas.Other = { type: 'string' };
  cache.run(args, () => 'first');
  spec.components.examples.greeting.value = 'hi';
  assert.equal(cache.run(args, () => 'second'), 'second');
  spec.components.schemas.Other.type = 'number';
  assert.equal(cache.run(args, () => 'third'), 'third');
});

test('pointer escaping matches the pinned Fern resolver', (t) => {
  const { args, cache } = fixture(t);
  args.propertySchema = { $ref: '#/components/schemas/a~1b~0c' };
  args.context.spec.components.schemas['a/b~0c'] = { type: 'string' };
  cache.run(args, () => 'first');
  args.context.spec.components.schemas['a/b~0c'].type = 'number';
  assert.equal(cache.run(args, () => 'second'), 'second');
});

test('external references bypass caching instead of risking stale content', (t) => {
  const { args, cache } = fixture(t);
  args.context.spec.components.schemas.Voice = { $ref: 'https://example.com/types.json#/Voice' };
  assert.equal(cache.run(args, () => 'first'), 'first');
  assert.equal(cache.run(args, () => 'second'), 'second');
  assert.equal(cache.stats.skipped, 2);
});

test('media request and response examples include their referenced schemas', (t) => {
  const { args, cache } = fixture(t);
  const media = { context: args.context, breadcrumbs: ['response'], mediaExampleArgs: { schema: args.propertySchema, example: undefined } };
  cache.run(media, () => 'marin');
  args.context.spec.components.schemas.Voice.enum = ['cedar'];
  assert.equal(cache.run(media, () => 'cedar'), 'cedar');
});
