name: Fern Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-fern

      - name: Check API is valid
        run: node scripts/fern/run.cjs check
