name: Update OpenAPI Specification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update OpenAPI Spec
        id: sync-openapi
        uses: fern-api/sync-openapi@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'update-openapi-spec'
          update_from_source: true
          add_timestamp: true
      - name: Enable auto-merge
        if: steps.sync-openapi.outputs.pr_number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.sync-openapi.outputs.pr_number }} --auto --squash
