name: Update OpenAPI Specification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update OpenAPI Spec
        id: sync-openapi
        uses: fern-api/sync-openapi@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'update-openapi-spec'
          update_from_source: true
          add_timestamp: true
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Wait a moment for PR to be fully created
          sleep 5
          # Get the most recent PR that starts with update-openapi-spec
          PR_NUMBER=$(gh pr list --head update-openapi-spec --json number,headRefName --jq 'map(select(.headRefName | startswith("update-openapi-spec"))) | .[0].number')
          if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
            echo "Found PR #$PR_NUMBER, enabling auto-merge"
            gh pr merge $PR_NUMBER --auto --squash
          else
            echo "No PR found for branch starting with update-openapi-spec"
          fi
